# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: "Node ${{ matrix.node }} - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        node: ['14', '16', 'latest']
        os: [ubuntu, macOS, windows]

    steps:
    - uses: actions/checkout@v1
    - uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install dependencies
      run: npx lerna bootstrap --no-ci
    - name: lint
      run: npm run lint
      env:
        CI: true
    - name: test
      run: npm test
      env:
        CI: true
